# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\"\x1c\n\x0cMessageType1\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0cMessageType2\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3')
)




_MESSAGETYPE1 = _descriptor.Descriptor(
  name='MessageType1',
  full_name='MessageType1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MessageType1.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=45,
)


_MESSAGETYPE2 = _descriptor.Descriptor(
  name='MessageType2',
  full_name='MessageType2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MessageType2.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['MessageType1'] = _MESSAGETYPE1
DESCRIPTOR.message_types_by_name['MessageType2'] = _MESSAGETYPE2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageType1 = _reflection.GeneratedProtocolMessageType('MessageType1', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGETYPE1,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:MessageType1)
  ))
_sym_db.RegisterMessage(MessageType1)

MessageType2 = _reflection.GeneratedProtocolMessageType('MessageType2', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGETYPE2,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:MessageType2)
  ))
_sym_db.RegisterMessage(MessageType2)


# @@protoc_insertion_point(module_scope)
